# Generated by Django for auctions app

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bid",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("listing_id", models.UUIDField(db_index=True)),
                ("bidder_id", models.UUIDField(db_index=True)),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("max_auto_bid", models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ("is_winning", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-amount", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuctionState",
            fields=[
                ("listing_id", models.UUIDField(primary_key=True, serialize=False)),
                ("current_price", models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ("bid_count", models.IntegerField(default=0)),
                ("high_bidder_id", models.UUIDField(blank=True, null=True)),
                ("end_time", models.DateTimeField()),
                ("is_extended", models.BooleanField(default=False)),
                ("status", models.CharField(default="OPEN", max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(fields=["listing_id", "-amount"], name="auctions_bi_listing_8b0b0d_idx"),
        ),
    ]
