# Generated by Django for wallet app

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WalletBalance",
            fields=[
                ("user_id", models.UUIDField(primary_key=True, serialize=False)),
                ("available", models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ("locked", models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ("pending", models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="DepositAddress",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                ("address", models.CharField(max_length=100, unique=True)),
                ("derivation_path", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                ("entry_type", models.CharField(choices=[("DEPOSIT", "Deposit"), ("WITHDRAWAL", "Withdrawal"), ("BID_LOCK", "Bid Lock"), ("BID_UNLOCK", "Bid Unlock"), ("ESCROW_LOCK", "Escrow Lock"), ("ESCROW_RELEASE", "Escrow Release"), ("PURCHASE", "Purchase"), ("SALE", "Sale"), ("FEE", "Fee"), ("REFUND", "Refund"), ("ADJUSTMENT", "Adjustment")], max_length=20)),
                ("debit", models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ("credit", models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ("balance_after", models.DecimalField(decimal_places=8, max_digits=20)),
                ("reference_type", models.CharField(max_length=50)),
                ("reference_id", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("idempotency_key", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DepositTransaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                ("address", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("txid", models.CharField(max_length=100)),
                ("confirmations", models.IntegerField(default=0)),
                ("status", models.CharField(choices=[("DETECTED", "Detected"), ("CONFIRMED", "Confirmed"), ("CREDITED", "Credited")], default="DETECTED", max_length=20)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("fee", models.DecimalField(decimal_places=8, max_digits=20)),
                ("destination_address", models.CharField(max_length=100)),
                ("txid", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(choices=[("REQUESTED", "Requested"), ("PROCESSING", "Processing"), ("SIGNED", "Signed"), ("BROADCAST", "Broadcast"), ("CONFIRMED", "Confirmed"), ("FAILED", "Failed")], default="REQUESTED", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Escrow",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("order_id", models.UUIDField()),
                ("buyer_id", models.UUIDField()),
                ("seller_id", models.UUIDField()),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("fee_amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("status", models.CharField(choices=[("LOCKED", "Locked"), ("RELEASED", "Released"), ("REFUNDED", "Refunded"), ("DISPUTED", "Disputed"), ("EXPIRED", "Expired")], default="LOCKED", max_length=20)),
                ("locked_at", models.DateTimeField(auto_now_add=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="walletbalance",
            constraint=models.CheckConstraint(check=models.Q(("available__gte", 0)), name="available_positive"),
        ),
        migrations.AddConstraint(
            model_name="walletbalance",
            constraint=models.CheckConstraint(check=models.Q(("locked__gte", 0)), name="locked_positive"),
        ),
        migrations.AddConstraint(
            model_name="walletbalance",
            constraint=models.CheckConstraint(check=models.Q(("pending__gte", 0)), name="pending_positive"),
        ),
        migrations.AlterUniqueTogether(
            name="deposittransaction",
            unique_together={("txid", "address")},
        ),
    ]
